# Generated by Django 6.0.3 on 2026-06-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='opciones',
            field=models.TextField(blank=True, null=True, verbose_name='Opciones (una por línea)'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='valor_seleccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('estrella', 'Calificación por estrellas (1-5)'), ('seleccion', 'Selección múltiple (opciones)')], default='estrella', max_length=20),
        ),
    ]
